name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '* */5 * * *'

  workflow_dispatch:

jobs:
 Auto:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto
        run: |
          git config --local user.email "lollipop@colsine.com"
          git config --local user.name "Colsine"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Nothing happened"
          git push
